name = "CartesianSphericalHarmonics"
uuid = "76434f01-525d-4cbb-bcb9-3cdf14f74cfc"
authors = ["Felix Gerick"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
